### ISSUE TITLE
Automatic Updates Should be Disabled in The Viewer

### ISSUE THREAD

**Issue by BrightCanopy** [BrightCanopy/BrightCanopy.github.io#10]
All updates should be through the Frame Admin console to avoid wasting any user's time. We can stay on top of updates from our side.

**Comment by ahgold** [comment]
Firestorm doesn't have automatic updates, so this would apply to the official SL viewer.

**Comment by BrightCanopy** [comment]
Yes, this will only be SL, the nag message on Firestorm won't be a problem because we'll keep on the  updates.

**Comment by BrightCanopy** [comment]
Added --chanel NoUpdate to the shortcut target string. (Thanks Whirly)
