### ISSUE TITLE
UK Keyboard layout still not recognised.

### ISSUE THREAD

**Issue by InaraPey** [BrightCanopy/BrightCanopy.github.io#11]
This is a dupe of "Frame doesnt know I'm using a UK keyboard so certain characters are typed wrongly in Firestorm", marked as Closed. Added as a new issue, as unable to re-open closed items. If existing issue re-opened (I have commented there), please close this one.

UK keyboard input still not recognised, despite feedback from Frame team. 

Frame does now report "ENG" as selected language, but UK English keyboards still map to US English keyboard layout.

For example, and as per original report:

Pressing the @ key on a UK keyboard causes " to be typed
Pressing the " key (SHIFT-2 on a UK keyboard layout) causes @ to be typed.

**Comment by BrightCanopy** [comment]
Thank you, Inara. I'll share that with Frame. I understand this is a brand new feature they are working on.

**Comment by BrightCanopy** [comment]
Marked as dup and original bug reopened.
