### ISSUE TITLE
Frame's graphic card not recognized on Firestorm

### ISSUE THREAD

**Issue by ahgold** [BrightCanopy/BrightCanopy.github.io#14]
On Firestorm, basic shaders (and anything beyond that) can't be enabled. This is probably because the graphics card is not being recognized. On the SL viewer, however, all shaders are enabled. This is probably due to the change in how the graphics cards are being recognized. There is some kind of benchmarking that LL has introduced recently but that hasn't quite made it into FS yet. I believe it's in the next FS version to be released soon.  It might be worth just waiting for the release rather than trying to fix it.

**Comment by BrightCanopy** [comment]
On whirly's advice changed the gpu_table*.txt in both the program and settings directories. The viewer may eventually overwrite this on launch so we need this added on the FS side.

**Comment by BrightCanopy** [comment]
We have a configuration fix. It will be nice to have the serverside GPU table updated to include Nvidia Grid, but FS will see an even more robust fix form LL upstream in the next release, so I'm closing this as fixed.
