### ISSUE TITLE
Firestorm/SL allow access to computer files. Intended?

### ISSUE THREAD

**Issue by Nethya** [BrightCanopy/BrightCanopy.github.io#15]
Firestorm/SL allow access to computer files through Preferences. Intended or not?

**Comment by BrightCanopy** [comment]
Yes, that's expected. The system is wiped after each session. We will have
persistence later, but that will still wipe anything not specifically
preserved for that user.

**Comment by BrightCanopy** [comment]
I'm going to close this as invalid, only because we meant to do that. Thanks for paying close attention. That's just what we need, @Nethya.
