### ISSUE TITLE
Camera view spins wildly in mouselook and when ALT camming

### ISSUE THREAD

**Issue by Whirly-Fizzle** [BrightCanopy/BrightCanopy.github.io#4]
- Enter mouselook and look around
- Exit mouselook.
- Hold down ALT and left click on an object and move mouse

**Observed**
When in mouselook or when ALT camming, camera view spins around or shoots off into the distance.

**Workaround**
Set DisableMouseWarp to TRUE in Debug settings
(Advanced menu in the top menu bar -> Debug Settings)
Setting DisableMouseWarp to TRUE does not completely fix the problem but it's a big improvement.

Usual causes of this problem can be found [HERE](http://wiki.phoenixviewer.com/fs_camera#camera_view_spinning_in_mouselook_or_when_alt_clicking_on_an_object)

**Testing system**

```
CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (3491.94 MHz)
Memory: 16268 MB
OS Version: Microsoft Windows 7 64-bit Service Pack 1 (Build 7601)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce GTX 750/PCIe/SSE2

Windows Graphics Driver Version: 9.18.0013.4788
OpenGL Version: 4.5.0 NVIDIA 347.88
```

**Comment by BrightCanopy** [comment]
I'll look at both the workaround and the main issue this evening. I'm not sure yet if the Windows settings will be captured into the published image, but I know the viewer settings will be. I'll find out.

**Comment by BrightCanopy** [comment]
The latest build has DisableMouseWarp set True. I wasn't able to reproduce any of the previous bad ALT Mouse or Mouselook behavior.  Please reopen if you still see issues. I suspect I'm missing something.
