### ISSUE TITLE
Unable to broadcast voice

### ISSUE THREAD

**Issue by Whirly-Fizzle** [BrightCanopy/BrightCanopy.github.io#5]
Voice connects and I can hear other users speaking on voice, however I am unable to broadcast my own voice.

Under Avatar -> Preferences -> Sound & Media -> Voice settings -> Audio Device Settings, I tried all available inputs and none picked up my Mic
Default
CABLE output (VB Audio Virtual)
Default System Device

Voice will broadcast on the same system using the standard Firestorm viewer.

When using CABLE output (VB Audio Virtual), very occasionally I will see my voice waves flash green for a second every now and again.

**Testing System**

```
CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (3491.94 MHz)
Memory: 16268 MB
OS Version: Microsoft Windows 7 64-bit Service Pack 1 (Build 7601)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce GTX 750/PCIe/SSE2

Windows Graphics Driver Version: 9.18.0013.4788
OpenGL Version: 4.5.0 NVIDIA 347.88
```

**Comment by BrightCanopy** [comment]
I know the Frame folks mentioned we may need some configuration for bi-directional sound. We can hold this open as the bug for that and close it when we get that resolved.

**Comment by nikolaboz** [comment]
This is indeed a feature we've have, though it's in alpha. Frame support should be able to help with it. : @Scriptgadget,  please reach out to them. 

Just to set expectations straight -- bi-directional audio works well on higher-end machine and on a good connection but encoding upstream audio in real-time in JS is CPU-intensive... I'd treat this feature as experimental and "use at your own risk" -- definitely don't want users to have high expectations about it.

**Comment by BrightCanopy** [comment]
Thanks @nikolaboz I filed a ticket last night and we're working through it. Although I probably should have broken it out separately from Flash/QT.

You make a good point on setting expectations.

**Comment by BrightCanopy** [comment]
Please retest voice now. I had good luck with the LL Viewer. I didn't hear any sound on the Firestorm viewer, but this may have been due to something on my end. I'll test it further myself in a little while.

**Comment by BrightCanopy** [comment]
blech, actually give it fifteen minutes or so.

**Comment by Whirly-Fizzle** [comment]
I was using Firefox and I reproduced the same problem when using Internet explorer.
Problem does NOT reproduce when using Chrome. Voice worked out of the box.

**Comment by BrightCanopy** [comment]
This seems to work great in Chrome, so I'm closing it. We can open a new bug if have further voice issues.
