### ISSUE TITLE
Flash media and Quicktime media will not play on Firestorm

### ISSUE THREAD

**Issue by Whirly-Fizzle** [BrightCanopy/BrightCanopy.github.io#8]
Flash media is either not installed or not enabled on the host system.
Quicktime does not appear to be installed.
This causes all Flash/Quicktime based parcel media, shared media/media on a prim and inworld TV's to be broken.
### Steps To Reproduce - Flash media
- Point parcel media or media on a prim to http://youtu.be/HE--nFfFLLk
- Attempt to watch the video.

**Observed**
Error message displays as shown in Fig 1 attached.

![fig 1](https://cloud.githubusercontent.com/assets/11756086/7129346/239e2738-e257-11e4-8350-74bce2df6391.jpg)
- Open internal web browser.
- Go to http://helpx.adobe.com/flash-player.html
- Click "Check Now"

**Observed**
Error message stating Flash player is not installed or not enabled - see Fig 2 attached.

![fig 2](https://cloud.githubusercontent.com/assets/11756086/7129345/239d44e4-e257-11e4-99f9-22819083f570.png)
### Steps To Reproduce - Quicktime media

Attempt to watch the following quicktime movie using shared media/media on a prim, parcel media or within the inworld browser: https://s3-us-west-1.amazonaws.com/bugislandtests/texture_rotate_animation_loop.mov

**Observed**
- Movie never loads on shared or parcel media - screen remains white.
- Internal browser gives the error "Frame load interupted by policy change" - see Fig 3 attached.

![fig 3](https://cloud.githubusercontent.com/assets/11756086/7129347/23a0153e-e257-11e4-9887-15a4e73fde5a.png)

Webkit itself is working as expected - ie) Login screen image loads, web profiles are viewable and inworld search is functional.

**Comment by nikolaboz** [comment]
This will be resolved by installing Flash/QT or whatever else is needed into the Sandbox and re-publishing to Production.

**Comment by BrightCanopy** [comment]
This is resolved. I was able to play a youtube video on a prim block and also see the video in the preview.
Worked with Support, but it turns out this is something we can do ourselves when installing the app, I'll just have to watch the order we do things.
